# Generated by Django 5.0.4 on 2024-05-06 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('imagen1', models.ImageField(upload_to='imagenes/')),
                ('imagen2', models.ImageField(upload_to='imagenes/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('componente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='djapi.componente')),
            ],
        ),
        migrations.CreateModel(
            name='ElectroAnalogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('imagen1', models.ImageField(upload_to='imagenes/')),
                ('imagen2', models.ImageField(upload_to='imagenes/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapi.user')),
            ],
        ),
    ]
