# Generated by Django 5.0.4 on 2024-05-06 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0004_componente_tipocomponente_electroanalogica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('imagen1', models.ImageField(upload_to='imagenes/')),
                ('imagen2', models.ImageField(upload_to='imagenes/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapi.user')),
            ],
        ),
    ]
