# Generated by Django 5.0.4 on 2024-05-11 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0005_electrodigital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electroanalogica',
            old_name='username',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='electrodigital',
            old_name='username',
            new_name='usuario',
        ),
    ]
