# Generated by Django 5.0.4 on 2024-05-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0011_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='componentes',
            field=models.ManyToManyField(related_name='proyectos', to='djapi.componente'),
        ),
    ]
