# Generated by Django 5.0.3 on 2024-05-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0016_accesorios_fecha_creacion_buzzers_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorios',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='buzzers',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='componente',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='electroanalogica',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='electrodigital',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='modulos',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='motores',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='optoelectronica',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='sensores',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='switches',
            name='usuario_nombre',
            field=models.CharField(default='', max_length=150),
        ),
    ]
