# Generated by Django 5.0.4 on 2024-05-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapi', '0017_accesorios_usuario_nombre_buzzers_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='id_original',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
